---
- name: Stoping previously started flink jobmanager
  shell: nohup bash {{ flink_dir }}/bin/jobmanager.sh stop-all

- name: Starting flink jobmanager
  shell: nohup bash {{ flink_dir }}/bin/jobmanager.sh start cluster

