---
- name: Fetch bench logs
  fetch:
    src: "{{ flamestream_dir }}/bench.log"
    dest: "{{ results_dir }}/flamestream/bench.log"
    flat: true

- name: Fetch latencies
  fetch:
    src: /tmp/lat.data
    dest: "{{ results_dir }}/flamestream/latency/lat.data"
    flat: true
