---
- name: Ensure the flink dir exists
  file:
    path: "{{ flink_dir }}"
    state: directory

- name: Ensure the tarball dir exists
  file:
    path: "{{ flink_tarball_dir }}"
    state: directory

- name: Download flink application
  get_url:
    url: "https://downloads.apache.org/flink/flink-1.12.1/flink-1.12.1-bin-scala_2.11.tgz"
    dest: "{{ flink_tarball_dir }}/flink.tgz"
  retries: 5

- name: Unpack flink tarball
  command: tar -xf {{ flink_tarball_dir }}/flink.tgz --strip-components=1
  args:
    chdir: "{{ flink_dir }}"
    creates: "{{ flink_dir }}/bin"

- name: Set up manager config
  template:
    src: workers.j2
    dest: "{{ flink_dir }}/conf/workers"

- name: Set up manager config2
  template:
    src: masters.j2
    dest: "{{ flink_dir }}/conf/masters"

- name: Set up common config
  template:
    src: flink-conf.yaml.j2
    dest: "{{ flink_dir }}/conf/flink-conf.yaml"
