---
- name: Ensure the flink dir exists
  file:
    path: "{{ flink_dir }}"
    state: directory

- name: Ensure the tarball dir exists
  file:
    path: "{{ flink_tarball_dir }}"
    state: directory

- name: Download flink application
  get_url:
    url: "{{ flink_url }}"
    dest: "{{ flink_tarball_dir }}/flin.tgz"

- name: Unpack flink tarball
  command: tar -xf {{ flink_tarball_dir }}/flin.tgz --strip-components=1
  args:
    chdir: "{{ flink_dir }}"
    creates: "{{ flink_dir }}/bin"

- name: Set up manager config
  template:
    src: slaves.j2
    dest: "{{ flink_dir }}/conf/slaves"

- name: Set up common config
  template:
    src: flink-conf.yaml.j2
    dest: "{{ flink_dir }}/conf/flink-conf.yaml"
