---
- name: Ensure the flink dir exists
  file:
    path: "{{ flink_dir }}"
    state: directory

- name: Ensure the tarball dir exists
  file:
    path: "{{ flink_tarball_dir }}"
    state: directory

- name: Download flink application
  get_url:
    url: "https://archive.apache.org/dist/flink/flink-1.4.0/flink-1.4.0-bin-scala_2.11.tgz"
    checksum: "md5:https://archive.apache.org/dist/flink/flink-1.4.0/flink-1.4.0-bin-scala_2.11.tgz.md5"
    dest: "{{ flink_tarball_dir }}/flink.tgz"
  retries: 5
  register: result
  until: result is not failed

- name: Unpack flink tarball
  command: tar -xf {{ flink_tarball_dir }}/flink.tgz --strip-components=1
  args:
    chdir: "{{ flink_dir }}"
    creates: "{{ flink_dir }}/bin"

- name: Set up manager config
  template:
    src: slaves.j2
    dest: "{{ flink_dir }}/conf/slaves"

- name: Set up common config
  template:
    src: flink-conf.yaml.j2
    dest: "{{ flink_dir }}/conf/flink-conf.yaml"
