FROM java:alpine
MAINTAINER Marshalkin Nikita <marnikitta@gmail.com>

ENTRYPOINT ["/usr/bin/java", "-jar", "/datastreams-new-core-jar-with-dependencies.jar"]

COPY target/datastreams-new-core-jar-with-dependencies.jar /datastreams-new-core-jar-with-dependencies.jar